### ISSUE TITLE
Error: invalid_request Mismatching redirect URI.

### ISSUE THREAD

**Issue by alexschroeter** [jhnnsrs/lok-server#2]
To reproduce:

When I try to connect via tailscale I assume I have to choose the "Arkitekt Server" via the tailscale IP. So I set "adress of your host" to \<tailscale IP\>:8000 and "use".

Afterwards the Server is found and I can connect via "Login with ...." which brings me to the above mentioned error from the following url
`http://<Tailscale IP>:8000/o/authorize/?client_id=snfoinosinefsef&scopes=read%20write&response_type=code&redirect_uri=http%3A%2F%2F<Tailscale IP>%3A8010%2Fcallback&code_challenge=cT474bxpTkgBEvnW_F3EruJmRTqoMr6xIAGr8lSiEpc&code_challenge_method=S256`

**Comment by jhnnsrs** [comment]
Hi Alex,

Ah the Redirect URI mismatch, I guess this will be a common problem and might really need 
a) more documentation
b) a workaround.

The mismatch in redirect uri stems from the fact that you are using the web version to connect to an
Arkitekt instance that is running on a remote server. By default the authentication via Oauth2 requires that redirect_uris
are preconfigured when setting up the client (otherwise a harmful app could pose as the client and steal the auth-token). This is done in the `lok.yaml` config. You would need to add the tailscale ip into the allowed redirect uris.

```yaml lok.yaml
- client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.orkestrator
  name: orkestrator
  redirect_uris:
    - http://127.0.0.1/
    - http://127.0.0.1/callback
    - http://localhost:8010/callback
    - http://localhost:8010/
    - http://<TAILSCALE_UP>:8010/callback #this line here
  scopes:
    - read
    - write
  tenant: admin
  version: latest
  token: 293j40239j4023023n039j30sdofins3n09nw30d9n203nf03fsdfseoinsoeinfosein

```

This is one of the reasons why i recommend the orkestrator app, as here the redirection is pointing to the loopback address,
were we temporarily spawn a server.

Alternatively i could imaging that we include some logic in the "redirect_uri_validator" that would automatically allow redirects to the same host name of the server (but vary ports). I would put this in the dangerous category however. But it would increase the easy of configuration when using the web site.

I am a bit conflicted about this however, as browsers are getting more and more locked down on accessing local network resources anyway (thanks Google...). Is there a reason why you would prefer the website approach?
